
name: homelab-dev-stack

services:

  nginx:
    image: docker.io/nginx:1.27.0
    container_name: homelab-nginx
    restart: always
    env_file:
      - ../noproxy.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/public/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ./nginx/public/favicon.png:/usr/share/nginx/html/favicon.png:ro
    networks:
      - network-reverse-proxy


  # https://hub.docker.com/r/osixia/openldap
  openldap:
    image: docker.io/osixia/openldap
    container_name: homelab-openldap
    env_file:
      - ../noproxy.env
    environment:
      LDAP_ORGANISATION: "OpenLDAP"
      LDAP_DOMAIN: "openldap.com"
      LDAP_ADMIN_PASSWORD: "admin"
    networks:
      - network-reverse-proxy

  # https://hub.docker.com/r/osixia/phpldapadmin
  #   Login DN: "cn=admin,dc=openldap,dc=com"
  #   Password: "admin"
  phpldapadmin:
    image: docker.io/osixia/phpldapadmin
    container_name: homelab-phpldapadmin
    env_file:
      - ../noproxy.env
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    volumes:
      - volume-phpldapadmin:/var/www/phpldapadmin
    networks:
      - network-reverse-proxy
    depends_on:
      - openldap


  # https://docs.portainer.io/start/install-ce/server/docker/linux
  portainer:
    image: docker.io/portainer/portainer-ce:2.20.3
    container_name: homelab-portainer
    restart: always
    privileged: true
    env_file:
      - ../noproxy.env
    volumes:
      - /srv/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-reverse-proxy


  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: docker.io/gitlab/gitlab-ee:16.10.3-ee.0
    container_name: homelab-gitlab
    restart: always
    shm_size: 256m
    env_file:
      - ../noproxy.env
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://192.168.11.2/gitlab'
        gitlab_rails['time_zone'] = 'Tokyo'
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    networks:
      - network-reverse-proxy
      - network-gitlab

  # https://docs.gitlab.com/runner/install/docker.html
  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:latest
    container_name: homelab-gitlab-runner
    restart: always
    env_file:
      - ../proxy.env
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - volume-gitlab-runner:/home/gitlab-runner
    networks:
      - network-gitlab


  # https://github.com/jenkinsci/docker/blob/master/README.md
  jenkins:
    image: docker.io/jenkins/jenkins:lts
    container_name: homelab-jenkins
    env_file:
      - ../noproxy.env
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
    volumes:
      - volume-jenkins:/var/jenkins_home
    networks:
      - network-reverse-proxy
      - network-jenkins

  jenkins-ssh:
    image: docker.io/jenkins/ssh-agent:latest
    container_name: homelab-jenkins-ssh
    env_file:
      - ../noproxy.env
    volumes:
      - volume-jenkins-ssh-agent:/home/jenkins/agent
      - volume-jenkins-ssh-tmp:/tmp
      - volume-jenkins-ssh-dot:/home/jenkins/.jenkins
      - volume-jenkins-ssh-run:/run
      - volume-jenkins-ssh-varrun:/var/run
    networks:
      - network-jenkins


  redmine:
    image: redmine:revpro
    build:
      context: .
      dockerfile: ./redmine/Dockerfile
    container_name: homelab-redmine
    env_file:
      - ../noproxy.env
    environment:
      REDMINE_DB_POSTGRES: homelab-redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine_user
      REDMINE_DB_PASSWORD: redmine_pass
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_PORT: 5432
    volumes:
      - volume-redmine:/usr/src/redmine/files
    networks:
      - network-reverse-proxy
      - network-redmine
    depends_on:
      redmine-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/redmine/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  redmine-db:
    image: docker.io/postgres:16.3
    container_name: homelab-redmine-db
    env_file:
      - ../noproxy.env
    environment:
      POSTGRES_DB:       redmine
      POSTGRES_USER:     redmine_user
      POSTGRES_PASSWORD: redmine_pass
    volumes:
      - volume-redmine-db:/var/lib/postgresql/data
    networks:
      - network-redmine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # https://gethomepage.dev/latest/configs/docker/#using-docker-socket-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homelab-dockerproxy
    restart: unless-stopped
    privileged: true
    env_file:
      - ../noproxy.env
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Mounted as read-only
    networks:
      - network-homepage
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: 29s
      timeout: 5s
      retries: 3
      start_period: 21s

  # https://github.com/gethomepage/homepage/
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homelab-homepage
    restart: unless-stopped
    privileged: true
    env_file:
      - ../noproxy.env
    # environment:
    #   # use `id` command
    #   PUID: 1000
    #   PGID: 1000
    volumes:
      # Make sure your local config directory exists
      - ./homepage/config:/app/config
      # optional, for docker integrations
      # - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network-reverse-proxy
      - network-homepage
    depends_on:
      - dockerproxy


  # https://coder.com/docs/code-server/latest/install#docker
  coder:
    image: lscr.io/linuxserver/code-server:latest
    container_name: homelab-coder
    restart: always
    privileged: true
    env_file:
      - ../noproxy.env
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Tokyo
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
    networks:
      - network-reverse-proxy
    volumes:
      - /srv/coder/.local:/home/coder/.local
      - /srv/coder/.config:/home/coder/.config
      - /srv/coder/project:/home/coder/project
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/healthz"]
      interval: 1s
      timeout: 10s
      retries: 5


 # https://github.com/support-project/docker-knowledge/blob/master/docker-compose.yml
  knowledge:
    image: knowledge:revpro
    build:
      context: .
      dockerfile: ./knowledge/Dockerfile
    container_name: homelab-knowledge
    restart: always
    env_file:
      - ../noproxy.env
    volumes:
      - ./knowledge/custom_connection.xml:/root/.knowledge/custom_connection.xml
      - /srv/knowledge:/root/.knowledge
    networks:
      - network-reverse-proxy
      - network-knowledge
    depends_on:
      - knowledge-db

  knowledge-db:
    image: docker.io/postgres:9
    container_name: homelab-knowledge-db
    restart: always
    env_file:
      - ../noproxy.env
    environment:
      - POSTGRES_USER=knowledge_user
      - POSTGRES_PASSWORD=knowledge_password
      - POSTGRES_DB=knowledge_database
    volumes:
      # - /srv/knowledge-db/initdb:/docker-entrypoint-initdb.d
      - /srv/knowledge-db/data:/var/lib/postgresql/data
    networks:
      - network-knowledge


  nextcloud:
    image: docker.io/nextcloud
    container_name: homelab-nextcloud
    restart: always
    env_file:
      - ../noproxy.env
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=nextcloud_password
    volumes:
      - /srv/nextcloud:/var/www/html
      - ./nextcloud/setup.sh:/root/setup.sh
    networks:
      - network-reverse-proxy
      - network-nextcloud

  nextcloud-db:
    image: docker.io/mariadb
    container_name: homelab-nextcloud-db
    restart: always
    env_file:
      - ../noproxy.env
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_ROOT_PASSWORD=nextcloud_root_pw
      - MARIADB_USER=nextcloud_user
      - MARIADB_PASSWORD=nextcloud_password
    volumes:
      - /srv/nextcloud-db:/var/lib/mysql
    networks:
      - network-nextcloud


  # Initial Setup: username=admin, password=admin
  # DataSource: http://prometheus:9090
  # https://zenn.dev/aobaiwaki/articles/a612bf497c59ca
  # Import: https://grafana.com/grafana/dashboards/1860-node-exporter-full/
  # Import: https://grafana.com/grafana/dashboards/11600-docker-container/
  # https://github.com/rvva/nginx-prometheus-grafana/blob/main/docker-compose.yml
  grafana:
    image: docker.io/grafana/grafana
    container_name: homelab-grafana
    restart: always
    env_file:
      - ../noproxy.env
    environment:
      GF_SERVER_ROOT_URL: http://homelab-grafana:3000/grafana/
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      DS_PROMETHEUS: homelab-prometheus
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/docker.json:/var/lib/grafana/dashboards/docker.json
      - ./grafana/machine.json:/var/lib/grafana/dashboards/machine.json
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
    networks:
      - network-reverse-proxy
      - network-grafana

  prometheus:
    image: docker.io/prom/prometheus
    container_name: homelab-prometheus
    restart: always
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    env_file:
      - ../noproxy.env
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - volume-prometheus:/prometheus
    networks:
      - network-grafana

  exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: homelab-node-exporter
    restart: always
    env_file:
      - ../noproxy.env
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - network-grafana

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: homelab-cadvisor
    privileged: true
    env_file:
      - ../noproxy.env
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - network-grafana


networks:
  network-reverse-proxy:
    name: network-homelab-reverse-proxy
    driver: bridge
  network-gitlab:
    name: network-homelab-gitlab
  network-redmine:
    name: network-homelab-redmine
  network-homepage:
    name: network-homelab-homepage
  network-jenkins:
    name: network-homelab-jenkins
  network-knowledge:
    name: network-homelab-knowledge
  network-nextcloud:
    name: network-homelab-nextcloud
  network-grafana:
    name: network-homelab-grafana


volumes:
  volume-gitlab-runner:
    name: volume-homelab-gitlab-runner
  volume-redmine:
    name: volume-homelab-redmine
  volume-redmine-db:
    name: volume-homelab-redmine-db
  volume-jenkins:
    name: volume-homelab-jenkins
  volume-jenkins-ssh-tmp:
    name: volume-homelab-jenkins-ssh-tmp
  volume-jenkins-ssh-agent:
    name: volume-homelab-jenkins-ssh-agent
  volume-jenkins-ssh-dot:
    name: volume-homelab-jenkins-ssh-dot
  volume-jenkins-ssh-run:
    name: volume-homelab-jenkins-ssh-run
  volume-jenkins-ssh-varrun:
    name: volume-homelab-jenkins-ssh-varrun
  volume-prometheus:
    name: volume-homelab-prometheus
  volume-phpldapadmin:
    name: volume-homelab-openldap-ui
