
name: homelab-dev-stack

services:

  https-portal:
    image: steveltn/https-portal:1
    container_name: homelab-https-portal
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAINS: "localhost -> http://homelab-nginx:80"
      STAGE: "local"
    restart: always
    networks:
      - network-https

  nginx:
    image: docker.io/nginx:1.27.0
    container_name: homelab-nginx
    restart: always
    # ports:
    #   - 80:80
    #   - 443:443
    env_file:
      - ../base.env
    volumes:
      - ./nginx/public:/usr/share/nginx/html:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - network-https
      - network-reverse-proxy

  # https://hub.docker.com/r/osixia/openldap
  openldap:
    image: docker.io/osixia/openldap
    container_name: homelab-openldap
    env_file:
      - ../base.env
    environment:
      LDAP_ORGANISATION: "OpenLDAP"
      LDAP_DOMAIN: "openldap.com"
      LDAP_ADMIN_PASSWORD: "admin"
    networks:
      - network-reverse-proxy

  # https://hub.docker.com/r/osixia/phpldapadmin
  #   Login DN: "cn=admin,dc=openldap,dc=com"
  #   Password: "admin"
  phpldapadmin:
    image: docker.io/osixia/phpldapadmin
    container_name: homelab-phpldapadmin
    env_file:
      - ../base.env
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: false
    volumes:
      - volume-phpldapadmin:/var/www/phpldapadmin
    networks:
      - network-reverse-proxy
    depends_on:
      - openldap


  # https://docs.portainer.io/start/install-ce/server/docker/linux
  portainer:
    image: docker.io/portainer/portainer-ce:2.20.3
    container_name: homelab-portainer
    restart: always
    privileged: true
    env_file:
      - ../base.env
    volumes:
      - /srv/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-reverse-proxy


  # https://docs.gitlab.com/ee/install/docker.html
  gitlab:
    image: docker.io/gitlab/gitlab-ee:16.10.3-ee.0
    container_name: homelab-gitlab
    restart: always
    shm_size: 256m
    # ports:
    #   - 30080:80
      # - 30443:443
    #   # - 30022:80
    #   - 5000:5000
    env_file:
      - ../base.env
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/etc/gitlab/omnibus_config.rb')"
    volumes:
      - volume-gitlab-config:/etc/gitlab
      - volume-gitlab-log:/var/log/gitlab
      - volume-gitlab-data:/var/opt/gitlab
      - ./gitlab/omnibus_config.rb:/etc/gitlab/omnibus_config.rb
    networks:
      - network-reverse-proxy
      - network-gitlab
      - network-prometheus
      - network-grafana

  # https://docs.gitlab.com/runner/install/docker.html
  gitlab-runner:
    image: docker.io/gitlab/gitlab-runner:alpine
    container_name: homelab-gitlab-runner
    restart: always
    env_file:
      - ../base.env
      - ../proxy.env
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - /srv/gitlab-runner/home:/home/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-gitlab


  # https://docs.kroki.io/kroki/setup/use-docker-or-podman/#_run_multiple_kroki_containers_together
  kroki:
    image: docker.io/yuzutech/kroki
    container_name: homelab-kroki
    env_file:
      - ../base.env
    environment:
      - KROKI_MERMAID_HOST=kroki-mermaid
      - KROKI_BPMN_HOST=kroki-bpmn
      - KROKI_EXCALIDRAW_HOST=kroki-excalidraw
    networks:
      - network-reverse-proxy
      - network-kroki
    depends_on:
      - kroki-mermaid
      - kroki-bpmn
      - kroki-excalidraw

  kroki-mermaid:
    image: docker.io/yuzutech/kroki-mermaid
    container_name: homelab-kroki-mermaid
    env_file:
      - ../base.env
    networks:
      - network-kroki

  kroki-bpmn:
    image: docker.io/yuzutech/kroki-bpmn
    container_name: homelab-kroki-bpmn
    env_file:
      - ../base.env
    networks:
      - network-kroki

  kroki-excalidraw:
    image: docker.io/yuzutech/kroki-excalidraw
    container_name: homelab-kroki-excalidraw
    env_file:
      - ../base.env
    networks:
      - network-kroki


  # https://github.com/jenkinsci/docker/blob/master/README.md
  jenkins:
    image: docker.io/jenkins/jenkins:lts
    container_name: homelab-jenkins
    env_file:
      - ../base.env
      - ../proxy.env
    environment:
      - "JENKINS_OPTS=--prefix=/jenkins"
    volumes:
      - volume-jenkins:/var/jenkins_home
    networks:
      - network-reverse-proxy
      - network-jenkins

  jenkins-ssh:
    image: docker.io/jenkins/ssh-agent:latest
    container_name: homelab-jenkins-ssh
    env_file:
      - ../base.env
    volumes:
      - volume-jenkins-ssh-agent:/home/jenkins/agent
      - volume-jenkins-ssh-tmp:/tmp
      - volume-jenkins-ssh-dot:/home/jenkins/.jenkins
      - volume-jenkins-ssh-run:/run
      - volume-jenkins-ssh-varrun:/var/run
    networks:
      - network-jenkins

  # ID:admin PW:admin
  redmine:
    image: redmine:revpro
    build:
      context: .
      dockerfile: ./redmine/Dockerfile
    container_name: homelab-redmine
    env_file:
      - ../base.env
    environment:
      REDMINE_DB_POSTGRES: homelab-redmine-db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine_user
      REDMINE_DB_PASSWORD: redmine_pass
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_PORT: 5432
    volumes:
      - volume-redmine:/usr/src/redmine/files
    networks:
      - network-reverse-proxy
      - network-redmine
    depends_on:
      redmine-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/redmine/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s


  redmine-db:
    image: docker.io/postgres:16.3
    container_name: homelab-redmine-db
    env_file:
      - ../base.env
    environment:
      POSTGRES_DB:       redmine
      POSTGRES_USER:     redmine_user
      POSTGRES_PASSWORD: redmine_pass
    volumes:
      - volume-redmine-db:/var/lib/postgresql/data
    networks:
      - network-redmine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

  # https://gethomepage.dev/latest/configs/docker/#using-docker-socket-proxy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homelab-dockerproxy
    restart: unless-stopped
    privileged: true
    env_file:
      - ../base.env
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    networks:
      - network-homepage
    healthcheck:
      test: wget --spider http://localhost:2375/version || exit 1
      interval: 29s
      timeout: 5s
      retries: 3
      start_period: 21s

  # https://github.com/gethomepage/homepage/
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homelab-homepage
    restart: unless-stopped
    privileged: true
    env_file:
      - ../base.env
    # environment:
    #   # use `id` command
    #   PUID: 1000
    #   PGID: 1000
    volumes:
      # Make sure your local config directory exists
      - ./homepage/config:/app/config
      # optional, for docker integrations
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network-reverse-proxy
      - network-homepage
    depends_on:
      - dockerproxy


  # https://coder.com/docs/code-server/latest/install#docker
  coder:
    image: lscr.io/linuxserver/code-server:latest
    container_name: homelab-coder
    restart: always
    privileged: true
    env_file:
      - ../base.env
      # - ../proxy.env
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Tokyo
      - PASSWORD= #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD= #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
    networks:
      - network-reverse-proxy
    volumes:
      - /srv/coder/.local:/home/coder/.local
      - /srv/coder/.config:/home/coder/.config
      - /srv/coder/project:/home/coder/project
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/healthz"]
      interval: 1s
      timeout: 10s
      retries: 5


 # https://github.com/support-project/docker-knowledge/blob/master/docker-compose.yml
  knowledge:
    image: knowledge:revpro
    build:
      context: .
      dockerfile: ./knowledge/Dockerfile
    container_name: homelab-knowledge
    restart: always
    env_file:
      - ../base.env
    volumes:
      - ./knowledge/custom_connection.xml:/root/.knowledge/custom_connection.xml
      - /srv/knowledge:/root/.knowledge
    networks:
      - network-reverse-proxy
      - network-knowledge
    depends_on:
      - knowledge-db

  knowledge-db:
    image: docker.io/postgres:9
    container_name: homelab-knowledge-db
    restart: always
    env_file:
      - ../base.env
    environment:
      - POSTGRES_USER=knowledge_user
      - POSTGRES_PASSWORD=knowledge_password
      - POSTGRES_DB=knowledge_database
    volumes:
      # - /srv/knowledge-db/initdb:/docker-entrypoint-initdb.d
      - /srv/knowledge-db/data:/var/lib/postgresql/data
    networks:
      - network-knowledge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s


  nextcloud:
    image: docker.io/nextcloud
    container_name: homelab-nextcloud
    restart: always
    env_file:
      - ../base.env
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=nextcloud_password
    volumes:
      - /srv/nextcloud:/var/www/html
      - ./nextcloud/setup.sh:/root/setup.sh
    networks:
      - network-reverse-proxy
      - network-nextcloud
    depends_on:
      - nextcloud-db

  # https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/
  nextcloud-db:
    image: docker.io/mariadb
    container_name: homelab-nextcloud-db
    restart: always
    env_file:
      - ../base.env
    environment:
      - MARIADB_DATABASE=nextcloud
      - MARIADB_ROOT_PASSWORD=nextcloud_root_pw
      - MARIADB_USER=nextcloud_user
      - MARIADB_PASSWORD=nextcloud_password
    volumes:
      - /srv/nextcloud-db:/var/lib/mysql
    networks:
      - network-nextcloud
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3


  # https://miniflux.app/docs/docker.html
  # https://miniflux.app/docs/howto.html#reverse-proxy-subfolder
  miniflux:
    image: miniflux/miniflux:latest
    container_name: homelab-miniflux
    env_file:
      - ../base.env
    environment:
      - DATABASE_URL=postgres://miniflux_user:miniflux_pass@miniflux-db/miniflux_base?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - BASE_URL=http://192.168.11.2/miniflux/
    networks:
      - network-reverse-proxy
      - network-miniflux
    depends_on:
      miniflux-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]

  miniflux-db:
    image: postgres:15
    container_name: homelab-miniflux-db
    env_file:
      - ../base.env
    environment:
      - POSTGRES_USER=miniflux_user
      - POSTGRES_PASSWORD=miniflux_pass
      - POSTGRES_DB=miniflux_base
    volumes:
      - volume-miniflux-db:/var/lib/postgresql/data
    networks:
      - network-miniflux
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux_user"]
      interval: 10s
      start_period: 30s


  # # https://doc.wallabag.org/en/admin/installation/installation.html#installation-with-docker
  # # https://hub.docker.com/r/wallabag/wallabag/
  # wallabag:
  #   image: wallabag/wallabag
  #   container_name: homelab-wallabag
  #   ports:
  #     - 8585:80
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=wallaroot
  #     - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
  #     - SYMFONY__ENV__DATABASE_HOST=wallabag-db
  #     - SYMFONY__ENV__DATABASE_PORT=3306
  #     - SYMFONY__ENV__DATABASE_NAME=wallabag_data
  #     - SYMFONY__ENV__DATABASE_USER=wallabag_user
  #     - SYMFONY__ENV__DATABASE_PASSWORD=wallabag_pass
  #     - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
  #     - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
  #     - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
  #     - SYMFONY__ENV__FROM_EMAIL=wallabag@localhost
  #     # - SYMFONY__ENV__DOMAIN_NAME=https://your-wallabag-instance.wallabag.org
  #     - SYMFONY__ENV__DOMAIN_NAME=http://localhost:8585
  #     - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
  #   # ports:
  #   #   - "80"
  #   volumes:
  #     - /opt/wallabag/images:/var/www/wallabag/web/assets/images
  #   networks:
  #     - network-reverse-proxy
  #     - network-wallabag
  #   healthcheck:
  #     test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
  #     interval: 1m
  #     timeout: 3s
  #   depends_on:
  #     - wallabag-db
  #     - wallabag-redis

  # wallabag-db:
  #   image: mariadb
  #   container_name: homelab-wallabag-db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=wallaroot
  #   volumes:
  #     - /opt/wallabag/data:/var/lib/mysql
  #   networks:
  #     - network-wallabag
  #   # healthcheck:
  #   #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #   #   interval: 20s
  #   #   timeout: 3s
  #   healthcheck:
  #     test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
  #     start_period: 1m
  #     start_interval: 10s
  #     interval: 1m
  #     timeout: 5s
  #     retries: 3

  # wallabag-redis:
  #   image: redis:alpine
  #   container_name: homelab-wallabag-redis
  #   networks:
  #     - network-wallabag
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 20s
  #     timeout: 3s


  # Initial Setup: username=admin, password=admin
  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/gitlab/#configure-gitlab-authentication-client-using-the-grafana-configuration-file
  grafana:
    image: docker.io/grafana/grafana
    container_name: homelab-grafana
    restart: always
    env_file:
      - ../base.env
    environment:
      # GF_SERVER_ROOT_URL: http://homelab-grafana:3000/grafana/
      GF_SERVER_ROOT_URL: http://192.168.11.2/grafana/
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_USERS_DEFAULT_THEME: light
      DS_PROMETHEUS: homelab-prometheus
      GF_AUTH_GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GF_AUTH_GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      GF_AUTH_GITLAB_ENABLED: true
      GF_AUTH_GITLAB_USE_REFRESH_TOKEN: true
      GF_AUTH_GITLAB_AUTH_URL: ${GITLAB_HOST}/oauth/authorize
      GF_AUTH_GITLAB_TOKEN_URL: ${GITLAB_HOST}/oauth/token
      GF_AUTH_GITLAB_API_URL: ${GITLAB_HOST}/api/v4
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - network-reverse-proxy
      - network-grafana
    depends_on:
      - prometheus

  prometheus:
    image: docker.io/prom/prometheus
    container_name: homelab-prometheus
    restart: always
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    env_file:
      - ../base.env
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - volume-prometheus:/prometheus
    networks:
      - network-grafana
      - network-prometheus
    depends_on:
      - nginx-exporter
      - node-exporter
      - cadvisor

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: homelab-nginx-exporter
    restart: always
    command:
      - --nginx.scrape-uri=http://homelab-nginx:8080/stub_status
    env_file:
      - ../base.env
    networks:
      - network-prometheus
      - network-reverse-proxy

  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: homelab-node-exporter
    restart: always
    command:
      - "--path.rootfs=/host"
    env_file:
      - ../base.env
    volumes:
      - /:/host:ro,rslave
    networks:
      - network-prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: homelab-cadvisor
    privileged: true
    env_file:
      - ../base.env
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - network-prometheus

  jupyterlab:
    image: jupyterlab:localbuild
    build:
      context: ./jupyterlab
      dockerfile: ./Dockerfile
    container_name: homelab-jupyterlab
    privileged: true
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --config='/root/workspace/jupyter_notebook_config.py' --NotebookApp.token='k5-mot'
    ports:
      - 8888:8888
    env_file:
      - ../base.env
    volumes:
      - /srv/jupyterlab/workspace:/root/workspace
    networks:
      - network-reverse-proxy
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

networks:
  network-https:
    name: homelab-network-https
  network-reverse-proxy:
    name: homelab-network-reverse-proxy
    driver: bridge
  network-gitlab:
    name: homelab-network-gitlab
  network-kroki:
    name: homelab-network-kroki
  network-redmine:
    name: homelab-network-redmine
  network-homepage:
    name: homelab-network-homepage
  network-jenkins:
    name: homelab-network-jenkins
  network-knowledge:
    name: homelab-network-knowledge
  network-nextcloud:
    name: homelab-network-nextcloud
  network-grafana:
    name: homelab-network-grafana
  network-prometheus:
    name: homelab-network-prometheus
  network-miniflux:
    name: homelab-network-miniflux
  network-wallabag:
    name: homelab-network-wallabag

volumes:
  volume-redmine:
    name: homelab-volume-redmine
  volume-redmine-db:
    name: homelab-volume-redmine-db
  volume-jenkins:
    name: homelab-volume-jenkins
  volume-jenkins-ssh-tmp:
    name: homelab-volume-jenkins-ssh-tmp
  volume-jenkins-ssh-agent:
    name: homelab-volume-jenkins-ssh-agent
  volume-jenkins-ssh-dot:
    name: homelab-volume-jenkins-ssh-dot
  volume-jenkins-ssh-run:
    name: homelab-volume-jenkins-ssh-run
  volume-jenkins-ssh-varrun:
    name: homelab-volume-jenkins-ssh-varrun
  volume-prometheus:
    name: homelab-volume-prometheus
  volume-phpldapadmin:
    name: homelab-volume-phpldapadmin
  volume-miniflux-db:
    name: homelab-volume-miniflux-db
  volume-gitlab-config:
    name: homelab-volume-gitlab-config
  volume-gitlab-log:
    name: homelab-volume-gitlab-log
  volume-gitlab-data:
    name: homelab-volume-gitlab-data
