name: ${STACK_PREFIX}-base-stack

services:

  pihole:
    image: pihole/pihole
    container_name: ${STACK_PREFIX}-pihole
    network_mode: host
    ports:
      - 8100:8100
    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: p@ssw0rd
      FTLCONF_LOCAL_IPV4: 192.168.11.30
      WEB_PORT: 8100
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  # https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
  traefik:
    image: traefik:v3.2
    container_name: ${STACK_PREFIX}-traefik
    restart: unless-stopped
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.ssh.address=:2222
      # - --certificatesresolvers.myresolver.acme.tlschallenge=true
      # - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.myresolver.acme.email=postmaster@example.com
      # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --accesslog=true
      - --accesslog.filePath=/logs/access.log
    ports:
      - 80:80
      - 443:443
      - 2222:2222
      - 8080:8080
    volumes:
      # - ./base/ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - shared
      - default

  whoami:
    image: traefik/whoami
    container_name: ${STACK_PREFIX}-whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # - traefik.docker.network=network-traefik
      - traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.service=whoami-svc
      - traefik.http.services.whoami-svc.loadbalancer.server.port=80
    networks:
      - shared
      - default

networks:
  shared:
    external: true
