---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Base:
  - traefik:
      href: http://192.168.11.30:8080/
      icon: traefik.png
      description: Traefik, The Cloud Native Edge Router
      server: my-docker
      container: homelab-traefik
  - whoami:
      href: http://192.168.11.30/whoami/
      icon: traefik.png
      description: Tiny Go webserver that prints OS information and HTTP request to output
      server: my-docker
      container: homelab-whoami
  - nginx:
      href: http://192.168.11.30/nginx/
      icon: nginx.png
      description: the world's most popular Web Server, high performance Load Balancer, Reverse Proxy, API Gateway and Content Cache.
      server: my-docker
      container: homelab-nginx

- Metrics:
  - prometheus:
      href: http://192.168.11.30/prometheus/
      icon: prometheus.svg
      description: a systems and service monitoring system.
      server: my-docker
      container: homelab-prometheus
  - nginx-exporter:
      href: http://192.168.11.30/nginx-exporter/
      icon: prometheus.svg
      description: NGINX Prometheus Exporter for NGINX and NGINX Plus
      server: my-docker
      container: homelab-nginx-exporter
  - node-exporter:
      href: http://192.168.11.30/node-exporter/
      icon: prometheus.svg
      description: Prometheus exporter for hardware and OS metrics
      server: my-docker
      container: homelab-node-exporter
  - cAdvisor:
      href: http://192.168.11.30/cadvisor/
      icon: cadvisor.png
      description: Analyzes resource usage and performance characteristics of running containers.
      server: my-docker
      container: homelab-cadvisor
  - dcgm-exporter:
      href: http://192.168.11.30/dcgm-exporter/
      icon: nvidia.png
      description: NVIDIA GPU metrics exporter for Prometheus leveraging DCGM
      server: my-docker
      container: homelab-dcgm-exporter

- Main:
  - Homepage:
      href: http://192.168.11.30/
      icon: homepage.png
      description: A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.
      server: my-docker
      container: homelab-homepage

- Git:
  - GitLab:
      href: http://192.168.11.30/gitlab/
      icon: gitlab.svg
      description: the most comprehensive AI-powered DevSecOps Platform.
      server: my-docker
      container: homelab-gitlab
  - GitLab-Runner:
      icon: gitlab.svg
      description: GitLab CI Multi Runner used to fetch and run pipeline jobs with GitLab CI
      server: my-docker
      container: homelab-gitlab-runner
  - Kroki:
      href: http://192.168.11.30/kroki/
      icon: diagrams-net.svg
      description: Creates diagrams from textual descriptions!
      server: my-docker
      container: homelab-kroki
  - Kroki-mermaid:
      icon: diagrams-net.svg
      description: mermaid
      server: my-docker
      container: homelab-kroki-mermaid
  - Kroki-bpmn:
      icon: diagrams-net.svg
      description: bpmn
      server: my-docker
      container: homelab-kroki-bpmn
  - Kroki-excalidraw:
      icon: diagrams-net.svg
      description: excalidraw
      server: my-docker
      container: homelab-kroki-excalidraw
  - Kroki-diagramsnet:
      icon: diagrams-net.svg
      description: diagramsnet
      server: my-docker
      container: homelab-kroki-diagramsnet

- Dev:
  - coder:
      href: http://192.168.11.30/coder/
      icon: code-server.png
      description: VS Code in the browser
      server: my-docker
      container: homelab-coder

- Ops:
  - Jenkins:
      href: http://192.168.11.30/jenkins/
      icon: jenkins.png
      description: Jenkins Continuous Integration and Delivery server.
      server: my-docker
      container: homelab-jenkins

- Prj:
  - Redmine:
      href: http://192.168.11.30/redmine/
      icon: si-redmine-#B32024
      description: Redmine is a flexible project management web application written using Ruby on Rails framework
      server: my-docker
      container: homelab-redmine
  - Knowledge:
      href: http://192.168.11.30/knowledge/
      icon: https://avatars.githubusercontent.com/u/10343544?s=200&v=4
      description: Free Knowledge Base System
      server: my-docker
      container: homelab-knowledge
  - Nextcloud:
      href: http://192.168.11.30/nextcloud/
      icon: nextcloud.svg
      description: A safe home for all your data.
      server: my-docker
      container: homelab-nextcloud
  - PostgreSQL for Redmine:
      icon: postgres.svg
      # description: DB
      server: my-docker
      container: homelab-redmine-db
  - PostgreSQL for Knowledge:
      icon: postgres.svg
      # description: DB
      server: my-docker
      container: homelab-knowledge-db
  - MariaDB for Nextcloud:
      icon: mariadb.svg
      # description: DB
      server: my-docker
      container: homelab-nextcloud-db

- Mon:
  - Portainer:
      href: http://192.168.11.30/portainer/
      icon: portainer.svg
      description: a lightweight service delivery platform for containerized applications
      server: my-docker
      container: homelab-portainer
  - Grafana:
      href: http://192.168.11.30/grafana/
      icon: grafana.svg
      description: Monitor your docker desktop instance from Grafana cloud.
      server: my-docker
      container: homelab-grafana
