{
 "title": "GitLab JiHu - Overview",
 "description": "Self-defined Dashboard for summary of GitLab JiHu\r\n",
 "tags": [ "GitLab" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br><h1><i><font color=#5991A7><b>GitLab Service Status</b></font></i></h1>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://www.cloudfoundry.org/wp-content/uploads/2017/10/icon_gitlab_cf@2x.png\" width=80px/></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "GitLab Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "topk(1, count by (version) (gitlab_build_info{job=~\"gitlab-workhorse\"}))",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job!~\"gitlab_exporter.*|node\",instance!~\".*:9168\"}) by (job) / count(up{job!~\"gitlab_exporter.*|node\",instance!~\".*:9168\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<br><h1><i><font color=#5991A7><b>Sidekiq Statistics</b></font></i></h1>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Background Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sidekiq_jobs_processed_total)",
     "legendFormat": "Processed"
    },
    { "expr": "max(sidekiq_jobs_failed_total)", "legendFormat": "Failed" },
    {
     "expr": "max(sidekiq_jobs_enqueued_size)",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "max(sidekiq_jobs_scheduled_size)",
     "legendFormat": "Scheduled"
    },
    { "expr": "max(sidekiq_jobs_retry_size)", "legendFormat": "Retry" },
    { "expr": "max(sidekiq_jobs_dead_size)", "legendFormat": "Dead" },
    { "expr": "max(sidekiq_processes_size)", "legendFormat": "Processes" }
   ]
  },
  {
   "title": "Queue Size Top 10",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, avg_over_time(sidekiq_queue_size{}[$__interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<br><h1><i><font color=#5991A7><b>Workhorse Statistics</b></font></i></h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Http Request Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (\n  rate(gitlab_workhorse_http_requests_total{instance=~\".*:9229\"}[$__interval])\n)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Workhorse Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(gitlab_workhorse_http_request_duration_seconds_bucket{instance=~\".*:9229\"}[$__interval])\n)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}