---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

startUrl: http://192.168.11.2/home/
base: /home/
favicon: http://192.168.11.2/favicon.ico
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 75 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 70 # 0-100
layout:
  Frontend Services in Operation:
    icon: si-docker-#0db7ed
    style: row
    columns: 4
  System Services in Operation:
    icon: si-docker-#0db7ed
    style: row
    columns: 4
  Backend Services in Operation:
    icon: si-docker-#0db7ed
    style: row
    columns: 4
  Services in Experiment:
    icon: si-docker-#0db7ed
    style: row
    columns: 4
showStats: true
headerStyle: boxed
