model_list:
  # OpenAI
  # - model_name: OpenAI-GPT-4o
  #   litellm_params:
  #     model: gpt-3.5-turbo-0125
  #     api_key: os.environ/OPENAI_API_KEY

  # Azure
  # - model_name: azure-gpt-4o
  #   litellm_params:
  #     model: azure/deployname # "azure/[deployment_name]"
  #     api_key: os.environ/AZURE_OPENNAI_API_KEY
  #     api_base: os.environ/AZURE_OPENAI_API_BASE

  # Anthropic
  # - model_name: Anthropic-Claude-3-Haiku
  #   litellm_params:
  #     model: claude-3-haiku-20240307
  #     api_key: os.environ/ANTROPIC_API_KEY

  # AWS
  # - model_name: AWS-Claude-3-Haiku
  #   litellm_params:
  #     model: anthropic.claude-3-haiku-20240307-v1:0
  #     aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
  #     aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  #     aws_region_name: os.environ/AWS_REGION_NAME

  # - model_name: llama3.1:8b
  #   litellm_params:
  #     model: ollama_chat/llama3.1:8b
  #     api_base: http://homelab-ollama:11434
  #   model_info:
  #     supports_function_calling: true

  # - model_name: deepseek-coder-v2:16b
  #   litellm_params:
  #     model: ollama_chat/deepseek-coder-v2:16b
  #     api_base: http://homelab-ollama:11434
  #   model_info:
  #     supports_function_calling: true

  # - model_name: elyza3:8b
  #   litellm_params:
  #     model: ollama_chat/elyza3:8b
  #     api_base: http://homelab-ollama:11434
  #   model_info:
  #     supports_function_calling: true

  # - model_name: llm-jp:13b
  #   litellm_params:
  #     model: ollama_chat/llm-jp:13b
  #     api_base: http://homelab-ollama:11434
  #   model_info:
  #     supports_function_calling: true

litellm_settings:
  num_retries: 3
  request_timeout: 60
  timeout: 60
  set_verbose: True
general_settings:
  master_key: sk-litellm
